services:
  web:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates   # bind mount (volumen local)
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=openti.com.bo
      - NGINX_PORT=80
